import Head from 'next/head'
// import Image from 'next/image'
// import Count from '../components/Count'
import Navbar from '../components/Navbar'
import Marketplace from '../components/Marketplace'
import styles from '../styles/App.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        {/* <Count /> */}
        <Navbar />
        <Marketplace />
      </main>
    </div>
  )
}
